//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2Desktop.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangedParts
    {
        public long ID { get; set; }
        public long EmergencyMaintenanceID { get; set; }
        public long PartID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual EmergencyMaintenances EmergencyMaintenances { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
